version = 0.1
[west]
[west.deploy]
[west.deploy.parameters]
region = "us-west-2"
stack_name = "terrahaxs-worker"
resolve_image_repos = true
resolve_s3 = true
capabilities = "CAPABILITY_NAMED_IAM"

[east]
[east.deploy]
[east.deploy.parameters]
region = "us-east-2"
stack_name = "terrahaxs-worker"
resolve_image_repos = true
resolve_s3 = true
capabilities = "CAPABILITY_NAMED_IAM"